# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://admin:Buddi2004@cluster0.3wbuoww.mongodb.net/
spring.data.mongodb.database=eislop

# Server
server.port=8082

# Authentication disabled; removing JWT-related properties

# Logging
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.com.eislop=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%t] %c{1.} - %m%n
