# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://admin:Buddi2004@cluster0.3wbuoww.mongodb.net/
spring.data.mongodb.database=eislop

# Server
server.port=8082

# JWT
app.jwt.secret=ReplaceWithAStrongSecretKeyChangeMe
app.jwt.expiration-ms=3600000
